-- Add many more daily prompts for variety
INSERT INTO public.daily_prompts (prompt_text, category) VALUES
  ('What are three things that brought you joy today?', 'gratitude'),
  ('Describe a moment when you felt truly at peace', 'reflection'),
  ('What is something new you learned recently?', 'growth'),
  ('Write a letter to your future self', 'imagination'),
  ('What are your dreams and aspirations right now?', 'goals'),
  ('Describe your ideal morning routine', 'daily'),
  ('What makes you feel most alive?', 'reflection'),
  ('Share a memory that always makes you smile', 'positive'),
  ('What would you do if you had no fear?', 'imagination'),
  ('Write about someone you admire and why', 'inspiration'),
  ('What are you looking forward to this week?', 'positive'),
  ('Describe a place where you feel completely yourself', 'reflection'),
  ('What is a goal you want to achieve this month?', 'goals'),
  ('Write about a random act of kindness you witnessed', 'gratitude'),
  ('What does success mean to you?', 'reflection'),
  ('Describe your favorite childhood memory', 'reflection'),
  ('What are three words that describe your current mood?', 'daily'),
  ('Write about a book, movie, or song that moved you', 'inspiration'),
  ('What habit would you like to develop?', 'growth'),
  ('Describe a perfect evening with loved ones', 'imagination'),
  ('What are you most proud of recently?', 'positive'),
  ('Write about a lesson you learned the hard way', 'growth'),
  ('What makes you feel grateful today?', 'gratitude'),
  ('Describe a moment when you felt truly understood', 'reflection'),
  ('What are your core values?', 'reflection'),
  ('Write about a time you stepped out of your comfort zone', 'growth'),
  ('What does happiness look like for you?', 'reflection'),
  ('Describe your favorite season and why you love it', 'daily'),
  ('What is something you want to let go of?', 'reflection'),
  ('Write about a skill you would love to master', 'goals'),
  ('What brings you comfort during difficult times?', 'reflection'),
  ('Describe your ideal creative space', 'imagination'),
  ('What are you curious about right now?', 'growth'),
  ('Write about a tradition that is meaningful to you', 'reflection'),
  ('What does self-care look like for you?', 'daily'),
  ('Describe a moment of unexpected beauty', 'positive'),
  ('What would you tell someone going through a hard time?', 'reflection'),
  ('Write about your favorite way to spend a weekend', 'daily'),
  ('What are three things you appreciate about yourself?', 'gratitude'),
  ('Describe a dream or vision that excites you', 'imagination'),
  ('What does balance mean in your life?', 'reflection'),
  ('Write about a friendship that changed you', 'inspiration'),
  ('What are you passionate about?', 'reflection'),
  ('Describe your relationship with time', 'reflection'),
  ('What gives your life meaning?', 'reflection'),
  ('Write about a place you would love to visit', 'imagination'),
  ('What are your favorite simple pleasures?', 'positive'),
  ('Describe how you handle stress and anxiety', 'growth'),
  ('What does authenticity mean to you?', 'reflection'),
  ('Write about a teacher or mentor who impacted you', 'inspiration')
ON CONFLICT (id) DO NOTHING;